// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(clippy::unnecessary_wraps)]
pub async fn de_operation_http_request<B>(
    #[allow(unused_variables)] request: http::Request<B>,
) -> std::result::Result<
    crate::input::OperationInput,
    aws_smithy_http_server::proto::rest_json_1::rejection::RequestRejection,
>
where
    B: aws_smithy_http_server::body::HttpBody + Send,
    B::Data: Send,
    aws_smithy_http_server::proto::rest_json_1::rejection::RequestRejection:
        From<<B as aws_smithy_http_server::body::HttpBody>::Error>,
{
    Ok({
        #[allow(unused_mut)]
        let mut input = crate::input::operation_input::Builder::default();
        #[allow(unused_variables)]
        let (parts, body) = request.into_parts();
        let bytes = hyper::body::to_bytes(body).await?;
        if !bytes.is_empty() {
            aws_smithy_http_server::protocols::content_type_header_classifier(
                &parts.headers,
                Some("application/json"),
            )?;
            input = crate::protocol_serde::shape_operation::de_operation(bytes.as_ref(), input)?;
        }
        input.build()
    })
}

#[allow(clippy::unnecessary_wraps)]
pub fn ser_operation_http_response(
    #[allow(unused_variables)] output: crate::output::OperationOutput,
) -> std::result::Result<
    aws_smithy_http_server::response::Response,
    aws_smithy_http_server::proto::rest_json_1::rejection::ResponseRejection,
> {
    Ok({
        #[allow(unused_mut)]
        let mut builder = http::Response::builder();
        builder = aws_smithy_http::header::set_response_header_if_absent(
            builder,
            http::header::CONTENT_TYPE,
            "application/json",
        );
        let http_status: u16 = 200;
        builder = builder.status(http_status);
        let payload =
            crate::protocol_serde::shape_operation_output::ser_operation_output_output(&output)?;
        let content_length = payload.len();
        builder = aws_smithy_http::header::set_response_header_if_absent(
            builder,
            http::header::CONTENT_LENGTH,
            content_length,
        );
        let body = aws_smithy_http_server::body::to_boxed(payload);
        builder.body(body)?
    })
}

pub(crate) fn de_operation(
    value: &[u8],
    mut builder: crate::input::operation_input::Builder,
) -> Result<
    crate::input::operation_input::Builder,
    aws_smithy_json::deserialize::error::DeserializeError,
> {
    let mut tokens_owned =
        aws_smithy_json::deserialize::json_token_iter(crate::protocol_serde::or_empty_doc(value))
            .peekable();
    let tokens = &mut tokens_owned;
    aws_smithy_json::deserialize::token::expect_start_object(tokens.next())?;
    loop {
        match tokens.next().transpose()? {
            Some(aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
            Some(aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
                match key.to_unescaped()?.as_ref() {
                    "message" => {
                        builder = builder.set_message(
                            aws_smithy_json::deserialize::token::expect_string_or_null(
                                tokens.next(),
                            )?
                            .map(|s| s.to_unescaped().map(|u| u.into_owned()))
                            .transpose()?,
                        );
                    }
                    _ => aws_smithy_json::deserialize::token::skip_value(tokens)?,
                }
            }
            other => {
                return Err(
                    aws_smithy_json::deserialize::error::DeserializeError::custom(format!(
                        "expected object key or end object, found: {:?}",
                        other
                    )),
                )
            }
        }
    }
    if tokens.next().is_some() {
        return Err(
            aws_smithy_json::deserialize::error::DeserializeError::custom(
                "found more JSON tokens after completing parsing",
            ),
        );
    }
    Ok(builder)
}
