// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[derive(
    std::clone::Clone, std::cmp::Eq, std::cmp::PartialEq, std::fmt::Debug, std::hash::Hash,
)]
pub struct OperationOutput {
    #[allow(missing_docs)] // documentation missing in model
    #[doc(hidden)]
    pub message: std::option::Option<std::string::String>,
}
impl OperationOutput {
    #[allow(missing_docs)] // documentation missing in model
    pub fn message(&self) -> std::option::Option<&str> {
        self.message.as_deref()
    }
}
impl OperationOutput {
    /// Creates a new builder-style object to manufacture [`OperationOutput`](crate::output::OperationOutput).
    pub fn builder() -> crate::output::operation_output::Builder {
        crate::output::operation_output::Builder::default()
    }
}
/// See [`OperationOutput`](crate::output::OperationOutput).
///
pub mod operation_output {

    impl std::convert::From<Builder> for crate::output::OperationOutput {
        fn from(builder: Builder) -> Self {
            builder.build()
        }
    }
    /// A builder for [`OperationOutput`](crate::output::OperationOutput).
    #[derive(std::clone::Clone, std::default::Default, std::fmt::Debug)]
    pub struct Builder {
        pub(crate) message: std::option::Option<std::string::String>,
    }
    impl Builder {
        #[allow(missing_docs)] // documentation missing in model
        pub fn message(mut self, input: std::option::Option<std::string::String>) -> Self {
            self.message = input;
            self
        }
        /// Consumes the builder and constructs a [`OperationOutput`](crate::output::OperationOutput).
        pub fn build(self) -> crate::output::OperationOutput {
            self.build_enforcing_all_constraints()
        }
        fn build_enforcing_all_constraints(self) -> crate::output::OperationOutput {
            crate::output::OperationOutput {
                message: self.message,
            }
        }
    }
}
